{% set version = "2.28.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cairodevice
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/Archive/cairoDevice/cairoDevice_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/cairoDevice_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cairoDevice/cairoDevice_{{ version }}.tar.gz
  sha256: 9385971cbc5a70f921f17745142ba99ff1e94c09e0523aa67d7c9255bd45e7b6

build:
  # GTK2 not available on Windows
  skip: true  # [win]
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - glib  # Needed for pkg-config to detect gtk2
    - gtk2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - gtk2

test:
  commands:
    - xvfb-run -a bash -c "$R -e \"library('cairoDevice')\""  # [linux]
    - $R -e "library('cairoDevice')"  # [osx]
    - "\"%R%\" -e \"library('cairoDevice')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=cairoDevice
  license: GPL-2.0-or-later
  summary: This device uses Cairo and GTK to draw to the screen, file (png, svg, pdf, and ps) or memory (arbitrary GdkDrawable or Cairo context). The screen device may be embedded into RGtk2 interfaces and supports all interactive features of other graphics devices, including getGraphicsEvent().
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: cairoDevice
# Version: 2.25
# Title: Embeddable Cairo Graphics Device Driver
# Author: Michael Lawrence
# Depends: R (>= 2.12.0)
# Imports: grDevices
# SystemRequirements: cairo (>= 1.0)
# Maintainer: Michael Lawrence <michafla@gene.com>
# Description: This device uses Cairo and GTK to draw to the screen, file (png, svg, pdf, and ps) or memory (arbitrary GdkDrawable or Cairo context). The screen device may be embedded into RGtk2 interfaces and supports all interactive features of other graphics devices, including getGraphicsEvent().
# Acknowledgements: Lyndon Drake (based on gtkDevice), Brian Ripley (updates for R 2.7), Mikhail Kondrin (Adobe->UTF8 translation), Duncan Murdoch (updates for R 2.12)
# License: GPL
# NeedsCompilation: yes
# Packaged: 2018-06-11 14:32:38 UTC; larman
# Repository: CRAN
# Date/Publication: 2018-06-12 13:33:44 UTC
