appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: q6+ihsNJkZL+zZ8Lqdrmc1LPSWINS3Zb9T1mVX4a24DAw/x6E7FTEKoD42Qsy5jGW9KB3fEpIYduT5td7LVIbjEP0gQCK6HN+CTv6F85olqu7AzEX3yulqjZxQG9zSgbitn7tNOSEne+HlszF7YMVJKYOBeVfrm3uP6EmmJBH/sZU5wH/aEhNzrefmQzcjIDp5Nuqxwh3wiVpm0/lUorp3a0sckrJnnTKJ5imGlCLQHPdDIoXGEkh8IhEK4bGzVEunAq2xVfB4+jwYtFxcuiqQWY0Ou/FKILiOttmUTQqeHpy95AL0QH89dZzCc3pLE6XtD7TX/lMNGepg5ltEy1o5wxmbpOpfI1ZMp1PEyA8dTrOxHOZobvqUX2yLw6F0bp3atonPf64+LTHTDogREpiTmKz1F6zyXYM22L7O2ld0Cu63FU2wnwI1qa2DVm00Ibk4WX07Bni/SG7GaXXnhegq79t4QVfAlj5T7G8DFGHVo4hQE6p+ELGfOZKsuBgq/0I0XpNaMw7QI+ArTXwIPI+LT98tqgx65dxBWWt3PNiUapPXGdNhZ8j+QTp1LzVPJARt6B4jfap9x32lL2ybrEXh3jhcii0RxPHw1VTc81xKt7EuZi4jqdCQeTA77pcL32byJFJZE8Spzra9+B7NtQpef6bRnBiGnxbUd80vJwULA=
